




CREATE TABLE bo_transaction
(
    session_id VARCHAR(100),
    bo_oper_id VARCHAR(100),
    ep_sttl_date VARCHAR(100),
    run_date VARCHAR(100),
    trx_type VARCHAR(100),
    message_type VARCHAR(100),
    clr_status VARCHAR(100),
    contract_type VARCHAR(100),
    card_number VARCHAR(100),
    account_number VARCHAR(100),
    sender_account_number VARCHAR(100),
    auth_code VARCHAR(100),
    arn VARCHAR(100),
    trans_date VARCHAR(100),
    clr_txn_amount VARCHAR(100),
    txn_currency VARCHAR(100),
    bill_amt VARCHAR(100),
    acct_curr VARCHAR(100),
    sttl_amount VARCHAR(100),
    st_rev VARCHAR(100),
    match_status VARCHAR(100),
    auth_id VARCHAR(100),
    mcc VARCHAR(100),
    merchant_number VARCHAR(100),
    terminal_number VARCHAR(100),
    merchant_name VARCHAR(100),
    merchant_city VARCHAR(100),
    merchant_country VARCHAR(100),
    auth_opr_id VARCHAR(100),
    base_ii_id VARCHAR(100),
    transaction_date VARCHAR(100),
    auth_card_number VARCHAR(100),
    reversal_flag VARCHAR(100),
    txn_amount VARCHAR(100),
    auth_currency VARCHAR(100),
    billing_amount VARCHAR(100),
    fees VARCHAR(100),
    billing_currency VARCHAR(100),
    status VARCHAR(100),
    txn_type_auth VARCHAR(100),
    auth_message_type VARCHAR(100),
    auth_mcc VARCHAR(100),
    auth_mid VARCHAR(100),
    auth_merchant_name VARCHAR(100),
    auth_city VARCHAR(100),
    auth_country VARCHAR(100),
    auth_tid VARCHAR(100),
    auth_acct_umber VARCHAR(100),
    pos_cond_code VARCHAR(100),
    utrnno VARCHAR(100),
    trace_number VARCHAR(100),
    trace_to_cbs VARCHAR(100),
    rrn VARCHAR(100),
    auth VARCHAR(100)
);